setup(installed React and some dependencies)
BuildForSDGCohort2/Team-091-Group-A-Frontend pull request #2
Opened 2020-09-01 12:39 UTC by its-nedum

Project Setup: Installed React and some dependencies

2020-09-01 12:54 UTC, uncleabbey requested changes
please add #3 into the pull request description

2020-09-01 15:24 UTC, uncleabbey approved these changes

2020-09-02 19:17 UTC, Jachrix approved these changes

2020-09-03 10:19 UTC, linda-oranya approved these changes

2020-09-03 18:07 UTC, merged